### ISSUE TITLE
Sm_agent top agent count is zero

### ISSUE THREAD

**Issue by sinu** [ppoffal/siteminder-Graylog-ContentPack#1]
Thanks for your Pack,  In my dashboard not able to see the top agent count ,Can you tell me how we can resolve this

**Comment by ppoffal** [comment]
Hi Sinu, Can you send a sample data from you siteminder log? 

In the mean time, here some stuffs you can test
For the top agent count you need to extract the sm_agent info from the log, in the content pack it will only works if you use the rsyslog template.

for this extraction I use a Grok_pattern, you can test the patter trying to extract the patter directly from you log message or test following these steps

system > inputs > your input > manage extractors >

Siteminder_SM_AzAccept
Siteminder_SM_AuthAttempt
Siteminder_SM_AuthLogout

click on Edit, now you can see the patter, some like this

\A%{HOSTNAME} sm\.access\.tag: %{sm_operation} %{sm_server} %{SYSLOG5424SD} "%{IP} uid=%{USERNAME},cn=%{cn},cn=%{cn},dc=%{dc},dc=com,dc=br" "%{sm_agent}-%{sm_agent_type}

to test against a specific log, you can click in choose another message and insert the message ID and Index.



Cheers!

**Comment by sinu** [comment]
Please see the log format from policy server

host123 sm.access.tag: AzAccept host123.demo.net [02/Feb/2016:03:46:02 -0800] "170.3.5.1 uid=1Monitor,ou=People,o=demo,o=dcx.com" "app.ext-nc.demo.com.dtr.agent GET /ExtendedWarrantyQuote/ScriptResource.axd?d=HddckhW-Gbg2JM5HGOpHlGjwm8Y_wl4tS6IDshC9Ma8iibyRiFhLqZkfQhx5nE2r_vDKF6jo12P-w_UatjhUFZTEUKHPOOyKSmp1gPYDEzGwsg3GLfqrJGopXxauYSt4YECwx3M8pw7jCXXhBjdbzZ410fs1&t=644ed049" [0000000000000000000000000c06d735-1284-56b096fa-14e

**Comment by ppoffal** [comment]
Hi Sinu. I found the problem
I am exctration the user dn using this pattern: cn=%{cn},cn=%{cn},dc=%{dc},dc=com,dc=br" 
So I will Create a universal patter for DN and submit the update.
Thankyou for the headsup. 
Cheers!

**Comment by ppoffal** [comment]
Fixed:
https://github.com/ppoffal/siteminder-Graylog-ContentPack/commit/1f1e22eef3ed1f5025f53a230fcfcbf21459b7d6

**Comment by ppoffal** [comment]
Fixed on: https://github.com/ppoffal/siteminder-Graylog-ContentPack/commit/1f1e22eef3ed1f5025f53a230fcfcbf21459b7d6

**Comment by ppoffal** [comment]
fixed on : https://github.com/ppoffal/siteminder-Graylog-ContentPack/commit/1f1e22eef3ed1f5025f53a230fcfcbf21459b7d6

**Comment by ppoffal** [comment]
already fixed
